// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHoliday(arg1) {
  return window['go']['main']['App']['AddHoliday'](arg1);
}

export function AddStudent(arg1, arg2) {
  return window['go']['main']['App']['AddStudent'](arg1, arg2);
}

export function ClearHolidays() {
  return window['go']['main']['App']['ClearHolidays']();
}

export function DeleteHoliday(arg1) {
  return window['go']['main']['App']['DeleteHoliday'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['main']['App']['DeleteStudent'](arg1);
}

export function ExportSchedule() {
  return window['go']['main']['App']['ExportSchedule']();
}

export function GetHolidays() {
  return window['go']['main']['App']['GetHolidays']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStudents() {
  return window['go']['main']['App']['GetStudents']();
}

export function GetTodayDuty() {
  return window['go']['main']['App']['GetTodayDuty']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ToggleDuty(arg1) {
  return window['go']['main']['App']['ToggleDuty'](arg1);
}

export function ToggleLunch(arg1) {
  return window['go']['main']['App']['ToggleLunch'](arg1);
}
