// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHoliday(arg1) {
  return window['go']['main']['App']['AddHoliday'](arg1);
}

export function AddStudent(arg1, arg2) {
  return window['go']['main']['App']['AddStudent'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearHolidays() {
  return window['go']['main']['App']['ClearHolidays']();
}

export function DebugLog(arg1) {
  return window['go']['main']['App']['DebugLog'](arg1);
}

export function DeleteHoliday(arg1) {
  return window['go']['main']['App']['DeleteHoliday'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['main']['App']['DeleteStudent'](arg1);
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function ExportSchedule() {
  return window['go']['main']['App']['ExportSchedule']();
}

export function GetActiveCountdownMusicData(arg1) {
  return window['go']['main']['App']['GetActiveCountdownMusicData'](arg1);
}

export function GetCountdownMusicData(arg1) {
  return window['go']['main']['App']['GetCountdownMusicData'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetHolidays() {
  return window['go']['main']['App']['GetHolidays']();
}

export function GetMissingHomework() {
  return window['go']['main']['App']['GetMissingHomework']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStudents() {
  return window['go']['main']['App']['GetStudents']();
}

export function GetTimetable() {
  return window['go']['main']['App']['GetTimetable']();
}

export function GetTodayDuty() {
  return window['go']['main']['App']['GetTodayDuty']();
}

export function ReportError(arg1) {
  return window['go']['main']['App']['ReportError'](arg1);
}

export function SaveMissingHomework(arg1) {
  return window['go']['main']['App']['SaveMissingHomework'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTimetable(arg1) {
  return window['go']['main']['App']['SaveTimetable'](arg1);
}

export function SelectCountdownMusics() {
  return window['go']['main']['App']['SelectCountdownMusics']();
}

export function SetFullscreen(arg1) {
  return window['go']['main']['App']['SetFullscreen'](arg1);
}

export function SyncHolidays() {
  return window['go']['main']['App']['SyncHolidays']();
}

export function ToggleDuty(arg1) {
  return window['go']['main']['App']['ToggleDuty'](arg1);
}

export function ToggleLunch(arg1) {
  return window['go']['main']['App']['ToggleLunch'](arg1);
}

export function ValidateRandomPool() {
  return window['go']['main']['App']['ValidateRandomPool']();
}
