// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function AddHoliday(arg1:string):Promise<void>;

export function AddStudent(arg1:number,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateResult>;

export function ClearHolidays():Promise<void>;

export function DebugLog(arg1:string):Promise<void>;

export function DeleteHoliday(arg1:string):Promise<void>;

export function DeleteStudent(arg1:number):Promise<void>;

export function DoUpdate():Promise<void>;

export function ExportSchedule():Promise<string>;

export function GetActiveCountdownMusicData(arg1:string):Promise<string>;

export function GetCountdownMusicData(arg1:number):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetHolidays():Promise<Array<string>>;

export function GetSettings():Promise<models.Settings>;

export function GetStudents():Promise<Array<models.Student>>;

export function GetTimetable():Promise<any>;

export function GetTodayDuty():Promise<models.TodayDutyResult>;

export function ReportError(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SaveTimetable(arg1:any):Promise<void>;

export function SelectCountdownMusics():Promise<Array<string>>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SyncHolidays():Promise<number>;

export function ToggleDuty(arg1:number):Promise<void>;

export function ToggleLunch(arg1:number):Promise<void>;

export function ValidateRandomPool():Promise<boolean>;
